#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Nimbuzz_Xamarin_Android_Db.Resource", IsApplication=true)]

namespace Nimbuzz_Xamarin_Android_Db
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int colorAccent = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int colorPrimary = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int colorPrimaryDark = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int orange = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int white = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fab_margin = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int nav_drawer_margin_offset = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int nav_header_height = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int nav_header_vertical_spacing = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int text_margin = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int about = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int btnSignin = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int exit = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int info = 2131296269;
			
			// aapt resource value: 0x7f090004
			public const int lbldb = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int logoutbtn = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int mainMenu = 2131296268;
			
			// aapt resource value: 0x7f090008
			public const int progressBar = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int scroll = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int textView2 = 2131296261;
			
			// aapt resource value: 0x7f090001
			public const int textView5 = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int textView6 = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int textViewDbEmail = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int textViewDbLink = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int txtPwd = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int txtUser = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int LoggedLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int loggedmenuoption = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menuoption = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int about = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int botid = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btn_login = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int coderdb = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int dbinfo2 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int dbinfo3 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int dbinfo4 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int exit = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int hello_db = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int info = 2131165204;
			
			// aapt resource value: 0x7f070009
			public const int lbl_dbh4ck = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int lbl_dbmail = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int lbl_pwd = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int lbl_username = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int login = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int logout = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int logtxt = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int ok = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int others = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int txt_pwd = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int txt_username = 2131165202;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
